version: '2'

services:
  visum-elasticsearch:
    container_name: "visum-elasticsearch"
    image: "elasticsearch:2.4.3"
    ports:
     - "9200:9200"
     - "9300:9300"
    networks:
      - visum-net
    restart: unless-stopped

  visum-grafana:
    container_name: "visum-grafana"
    image: "grafana/grafana"
    ports:
      - 3000:3000
    volumes:
      - ../grafana-data:/var/lib/grafana
    depends_on:
      - "visum-elasticsearch"
    networks:
      - visum-net
    restart: unless-stopped

  visum-core:
    build: .
    container_name: "visum-core"
    ports:
      - "8088:8088"
    depends_on:
      - "visum-elasticsearch"
    networks:
      - visum-net

networks:
  visum-net:
    driver: bridge